apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bootcamp.fullname" . }}
  labels:
    {{- include "bootcamp.labels" . | nindent 4 }}
data:
  BIND_ADDRESS: {{ .Values.config.bindAddress | quote }}
  {{- if .Values.upload.internal }}
  UPLOAD_SERVICE_URL: {{ .Values.config.uploadServiceURL | default (printf "http://%s:8080" (include "bootcamp.uploadName" .)) | quote }}
  {{- else }}
  UPLOAD_SERVICE_URL: {{ .Values.config.uploadServiceURL | required "config.uploadServiceURL is required when upload.internal is false" | quote }}
  {{- end }}
  COOKIE_SECURE: {{ .Values.config.cookieSecure | quote }}
  ALLOW_PRIVATE_UPLOADS: {{ .Values.config.allowPrivateUploads | quote }}
  ALLOW_SINGLE_USE_LINKS: {{ .Values.config.allowSingleUseLinks | quote }}
  {{- if .Values.config.replicatedSDKURL }}
  REPLICATED_SDK_URL: {{ .Values.config.replicatedSDKURL | quote }}
  {{- end }}
