apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bootcamp.fullname" . }}
  labels:
    {{- include "bootcamp.labels" . | nindent 4 }}
type: Opaque
stringData:
  UPLOAD_ADMIN_TOKEN: {{ .Values.secrets.uploadAdminToken | quote }}
  {{- with .Values.secrets.adminPassword }}
  ADMIN_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- if not .Values.postgres.internal }}
  DATABASE_URL: {{ .Values.secrets.databaseURL | quote }}
  {{- end }}
{{- if and .Values.gateway.tlsCert .Values.gateway.tlsKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bootcamp.fullname" . }}-tls
  labels:
    {{- include "bootcamp.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.gateway.tlsCert | quote }}
  tls.key: {{ .Values.gateway.tlsKey | quote }}
{{- end }}
