apiVersion: v1
kind: Service
metadata:
  name: {{ include "bootcamp.uploadName" . }}
  labels:
    {{- include "bootcamp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bootcamp.uploadSelectorLabels" . | nindent 4 }}
