apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: bootcamp
spec:
  title: Bootcamp
  icon: https://cdn-icons-png.flaticon.com/512/2716/2716054.png
  statusInformers:
    - deployment/bootcamp
    - deployment/bootcamp-upload
