apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: cloudnative-pg
  annotations:
    kots.io/exclude: 'repl{{ ConfigOptionEquals "postgres_type" "external" }}'
spec:
  chart:
    name: cloudnative-pg
    chartVersion: 0.28.0
  weight: 1
  helmUpgradeFlags:
    - --wait
    - --timeout=300s
  values: {}
  builder: {}
