apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: bootcamp
spec:
  chart:
    name: bootcamp
    chartVersion: 0.1.0
  weight: 2
  values:
    global:
      replicated:
        proxy:
          registryDomain: "registry.9265.gay"
    secrets:
      uploadAdminToken: repl{{ if ConfigOptionEquals "upload_type" "internal" }}{{ ConfigOption "upload_admin_token" }}{{ else }}{{ ConfigOption "external_upload_admin_token" }}{{ end }}
      adminPassword: repl{{ ConfigOption "admin_password" }}
    postgres:
      internal: repl{{ ConfigOptionEquals "postgres_type" "internal" }}
      storage:
        size: repl{{ ConfigOption "postgres_storage_size" }}
    upload:
      internal: repl{{ ConfigOptionEquals "upload_type" "internal" }}
      storage:
        size: repl{{ ConfigOption "upload_storage_size" }}
    config:
      cookieSecure: '{{repl if ConfigOptionEquals "ingress_type" "traefik_https" }}true{{repl else }}false{{repl end }}'
      replicatedSDKURL: "http://replicated:3000"
    gateway:
      host: repl{{ ConfigOption "hostname" }}
      tls: repl{{ ConfigOptionEquals "ingress_type" "traefik_https" }}
  optionalValues:
    - when: 'repl{{ ConfigOptionEquals "ingress_type" "nodeport" }}'
      recursiveMerge: true
      values:
        service:
          type: NodePort
    - when: 'repl{{ and (ConfigOptionEquals "ingress_type" "nodeport") (ConfigOptionNotEquals "nodeport_port" "") }}'
      recursiveMerge: true
      values:
        service:
          nodePort: repl{{ ConfigOption "nodeport_port" }}
    - when: 'repl{{ ConfigOptionEquals "postgres_type" "external" }}'
      recursiveMerge: true
      values:
        secrets:
          databaseURL: repl{{ ConfigOption "external_database_url" }}
    - when: 'repl{{ ConfigOptionEquals "upload_type" "external" }}'
      recursiveMerge: true
      values:
        config:
          uploadServiceURL: repl{{ ConfigOption "upload_service_url" }}
    - when: 'repl{{ ConfigOptionNotEquals "upload_ttl" "" }}'
      recursiveMerge: true
      values:
        upload:
          ttl: repl{{ ConfigOption "upload_ttl" }}
    - when: 'repl{{ ConfigOptionNotEquals "upload_max_bytes" "" }}'
      recursiveMerge: true
      values:
        upload:
          maxUploadBytes: repl{{ ConfigOption "upload_max_bytes" }}
  builder:
    # Builder renders the chart to collect images for the airgap bundle.
    # Override the proxy domain so images resolve to their original registries.
    global:
      replicated:
        proxy:
          registryDomain: ""
    image:
      repository: ghcr.io/ashjones-replicated/bootcamp
      tag: "sha-1462544"
    upload:
      image:
        repository: codeberg.org/sparrow/upload
        tag: "v2.0.0"
    replicated:
      replicaCount: 1
